
def common()
  use_frameworks!
  pod 'OhCrap', :path => '../'
end

target 'Example' do
  platform :ios, '8.0'
  common()
end

target 'ExampleMacOS' do
  platform :osx, '10.10'
  common()
end

target 'ExampleTVOS' do
    platform :tvos, '9.0'
    common()
end

target 'ExampleWatchOS Extension' do
    platform :watchos, '2.0'
    common()
end

target 'ExampleWatchOS' do
    platform :watchos, '2.0'
    common()
end
